// Generated by pnpm api:generate. Do not edit by hand.
import type { z } from "zod";
import type { Operation, OperationName } from "#/server/operations";

const routes = {
	"group.list": {
		method: "GET",
		path: "/v1/groups",
	},
	"group.create": {
		method: "POST",
		path: "/v1/groups",
	},
	"group.get": {
		method: "GET",
		path: "/v1/groups/:groupId",
	},
	"group.rename": {
		method: "PATCH",
		path: "/v1/groups/:groupId",
	},
	"group.delete": {
		method: "DELETE",
		path: "/v1/groups/:groupId",
	},
	"group.leave": {
		method: "POST",
		path: "/v1/groups/:groupId/leave",
	},
	"group.archive": {
		method: "POST",
		path: "/v1/groups/:groupId/archive",
	},
	"group.unarchive": {
		method: "POST",
		path: "/v1/groups/:groupId/unarchive",
	},
	"group.duplicate": {
		method: "POST",
		path: "/v1/groups/:groupId/duplicate",
	},
	"member.list": {
		method: "GET",
		path: "/v1/groups/:groupId/members",
	},
	"member.add": {
		method: "POST",
		path: "/v1/groups/:groupId/members",
	},
	"member.role": {
		method: "PATCH",
		path: "/v1/groups/:groupId/members/:userId",
	},
	"member.remove": {
		method: "DELETE",
		path: "/v1/groups/:groupId/members/:userId",
	},
	"member.weight": {
		method: "PATCH",
		path: "/v1/groups/:groupId/members/:userId/weight",
	},
	"member.merge": {
		method: "POST",
		path: "/v1/members/merge",
	},
	"invitation.mine": {
		method: "GET",
		path: "/v1/me/invitations",
	},
	"invitation.list": {
		method: "GET",
		path: "/v1/groups/:groupId/invitations",
	},
	"invitation.create": {
		method: "POST",
		path: "/v1/groups/:groupId/invitations",
	},
	"invitation.get": {
		method: "GET",
		path: "/v1/invitations/:invitationId",
	},
	"invitation.revoke": {
		method: "DELETE",
		path: "/v1/invitations/:invitationId",
	},
	"invitation.accept": {
		method: "POST",
		path: "/v1/invitations/:invitationId/accept",
	},
	"expense.list": {
		method: "GET",
		path: "/v1/groups/:groupId/expenses",
	},
	"expense.get": {
		method: "GET",
		path: "/v1/expenses/:expenseId",
	},
	"expense.preview": {
		method: "POST",
		path: "/v1/groups/:groupId/expenses/preview",
	},
	"expense.create": {
		method: "POST",
		path: "/v1/groups/:groupId/expenses",
	},
	"expense.update": {
		method: "PATCH",
		path: "/v1/expenses/:expenseId",
	},
	"expense.delete": {
		method: "DELETE",
		path: "/v1/expenses/:expenseId",
	},
	"expense.resplit": {
		method: "POST",
		path: "/v1/groups/:groupId/expenses/resplit",
	},
	"expense.report": {
		method: "GET",
		path: "/v1/groups/:groupId/reports/expenses",
	},
	"share.paid": {
		method: "POST",
		path: "/v1/expenses/:expenseId/shares/:userId/paid",
	},
	"share.unpaid": {
		method: "DELETE",
		path: "/v1/expenses/:expenseId/shares/:userId/paid",
	},
	"category.list": {
		method: "GET",
		path: "/v1/groups/:groupId/categories",
	},
	"category.suggest": {
		method: "GET",
		path: "/v1/groups/:groupId/categories/suggest",
	},
	"category.create": {
		method: "POST",
		path: "/v1/groups/:groupId/categories",
	},
	"category.update": {
		method: "PATCH",
		path: "/v1/groups/:groupId/categories/:ruleId",
	},
	"category.delete": {
		method: "DELETE",
		path: "/v1/groups/:groupId/categories/:ruleId",
	},
	"balance.get": {
		method: "GET",
		path: "/v1/groups/:groupId/balances",
	},
	"balance.crossGroup": {
		method: "GET",
		path: "/v1/me/balances",
	},
	"payment.intents": {
		method: "GET",
		path: "/v1/groups/:groupId/payment-intents",
	},
	"settlement.list": {
		method: "GET",
		path: "/v1/groups/:groupId/settlements",
	},
	"settlement.create": {
		method: "POST",
		path: "/v1/groups/:groupId/settlements",
	},
	"settlement.delete": {
		method: "DELETE",
		path: "/v1/settlements/:settlementId",
	},
	"activity.group": {
		method: "GET",
		path: "/v1/groups/:groupId/activity",
	},
	"activity.mine": {
		method: "GET",
		path: "/v1/me/activity",
	},
	"reminder.list": {
		method: "GET",
		path: "/v1/groups/:groupId/reminders",
	},
	"reminder.schedule": {
		method: "POST",
		path: "/v1/groups/:groupId/reminders",
	},
	"reminder.preferences.get": {
		method: "GET",
		path: "/v1/me/reminder-preferences",
	},
	"reminder.preferences.update": {
		method: "PATCH",
		path: "/v1/me/reminder-preferences",
	},
	"recurring.list": {
		method: "GET",
		path: "/v1/groups/:groupId/recurring-expenses",
	},
	"recurring.create": {
		method: "POST",
		path: "/v1/groups/:groupId/recurring-expenses",
	},
	"recurring.update": {
		method: "PATCH",
		path: "/v1/recurring-expenses/:templateId",
	},
	"recurring.delete": {
		method: "DELETE",
		path: "/v1/recurring-expenses/:templateId",
	},
} as const;

type OperationFor<Name extends OperationName> = Extract<
	Operation,
	{ name: Name }
>;
export type ApiInput<Name extends OperationName> = z.input<
	OperationFor<Name>["input"]
>;

export function createEventualClient(options: {
	baseUrl: string;
	apiKey: string;
}) {
	return {
		async invoke<Name extends keyof typeof routes>(
			name: Name,
			input: ApiInput<Name>,
			request: { idempotencyKey?: string; signal?: AbortSignal } = {},
		) {
			const route = routes[name];
			const values = input as Record<string, unknown>;
			const used = new Set<string>();
			const path = route.path.replace(
				/:([A-Za-z0-9_]+)/g,
				(_match, key: string) => {
					used.add(key);
					return encodeURIComponent(String(values[key]));
				},
			);
			const url = new URL(
				`api${path}`,
				options.baseUrl.endsWith("/") ? options.baseUrl : `${options.baseUrl}/`,
			);
			const headers = new Headers({
				Authorization: `Bearer ${options.apiKey}`,
			});
			if (request.idempotencyKey)
				headers.set("Idempotency-Key", request.idempotencyKey);
			let body: string | undefined;
			if (route.method === "GET") {
				for (const [key, value] of Object.entries(values)) {
					if (used.has(key) || value === undefined || value === null) continue;
					for (const item of Array.isArray(value) ? value : [value])
						url.searchParams.append(
							key,
							item instanceof Date ? item.toISOString() : String(item),
						);
				}
			} else {
				headers.set("Content-Type", "application/json");
				body = JSON.stringify(values);
			}
			const response = await fetch(url, {
				method: route.method,
				headers,
				body,
				signal: request.signal,
			});
			const result = await response.json();
			if (!response.ok)
				throw Object.assign(
					new Error(result?.error?.message ?? "API request failed"),
					{ status: response.status, details: result?.error },
				);
			return result as z.output<OperationFor<Name>["output"]>;
		},
	};
}
