import { writeFile } from "node:fs/promises";
import { resolve } from "node:path";

process.env.TURSO_DATABASE_URL ??= "file:./.api-client-generation.db";
process.env.BETTER_AUTH_SECRET ??= "api-client-generation-secret-32-characters";

const { operations } = await import("../src/server/operations");

const routes = Object.fromEntries(
	operations
		.map((operation) => [
			operation.name,
			{ method: operation.method, path: operation.path },
		]),
);

const source = `// Generated by bun run api:generate. Do not edit by hand.
import type { z } from "zod";
import type { Operation, OperationName } from "#/server/operations";

export const routes = ${JSON.stringify(routes, null, "\t")} as const;

type OperationFor<Name extends OperationName> = Extract<Operation, { name: Name }>;
export type ApiInput<Name extends OperationName> = z.input<OperationFor<Name>["input"]>;

export function createEventualClient(options: { baseUrl: string; apiKey: string }) {
\treturn {
\t\tasync invoke<Name extends keyof typeof routes>(
\t\t\tname: Name,
\t\t\tinput: ApiInput<Name>,
\t\t\trequest: { idempotencyKey?: string; signal?: AbortSignal } = {},
\t\t) {
\t\t\tconst route = routes[name];
\t\t\tconst values = input as Record<string, unknown>;
\t\t\tconst used = new Set<string>();
\t\t\tconst path = route.path.replace(/:([A-Za-z0-9_]+)/g, (_match, key: string) => {
\t\t\t\tused.add(key);
\t\t\t\treturn encodeURIComponent(String(values[key]));
\t\t\t});
\t\t\tconst url = new URL(\`api\${path}\`, options.baseUrl.endsWith("/") ? options.baseUrl : \`\${options.baseUrl}/\`);
\t\t\tconst headers = new Headers({ Authorization: \`Bearer \${options.apiKey}\` });
\t\t\tif (request.idempotencyKey) headers.set("Idempotency-Key", request.idempotencyKey);
\t\t\tlet body: string | undefined;
\t\t\tif (route.method === "GET") {
\t\t\t\tfor (const [key, value] of Object.entries(values)) {
\t\t\t\t\tif (used.has(key) || value === undefined || value === null) continue;
\t\t\t\t\tfor (const item of Array.isArray(value) ? value : [value])
\t\t\t\t\t\turl.searchParams.append(key, item instanceof Date ? item.toISOString() : String(item));
\t\t\t\t}
\t\t\t} else {
\t\t\t\theaders.set("Content-Type", "application/json");
\t\t\t\tbody = JSON.stringify(values);
\t\t\t}
\t\t\tconst response = await fetch(url, { method: route.method, headers, body, signal: request.signal });
\t\t\tconst result = await response.json();
\t\t\tif (!response.ok) throw Object.assign(new Error(result?.error?.message ?? "API request failed"), { status: response.status, details: result?.error });
\t\t\treturn result as z.output<OperationFor<Name>["output"]>;
\t\t},
\t};
}
`;

await writeFile(resolve("src/lib/api-client.gen.ts"), source);
