/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/app'
import { Route as ClaimGuestRouteImport } from './routes/claim-guest'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as HelpRouteImport } from './routes/help'
import { Route as LoginRouteImport } from './routes/login'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as ApiSplatRouteImport } from './routes/api/$'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as AppActivityRouteImport } from './routes/app/activity'
import { Route as AppSettingsRouteRouteImport } from './routes/app/settings/route'
import { Route as HelpIndexRouteImport } from './routes/help/index'
import { Route as HelpSlugRouteImport } from './routes/help/$slug'
import { Route as InviteInvitationIdRouteImport } from './routes/invite/$invitationId'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AppSettingsIndexRouteImport } from './routes/app/settings/index'
import { Route as AppSettingsApiKeysRouteImport } from './routes/app/settings/api-keys'
import { Route as AppSettingsProfileRouteImport } from './routes/app/settings/profile'
import { Route as AppGroupsGroupIdIndexRouteImport } from './routes/app/groups/$groupId/index'
import { Route as AppGroupsGroupIdExpensesExpenseIdRouteImport } from './routes/app/groups/$groupId/expenses/$expenseId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const ClaimGuestRoute = ClaimGuestRouteImport.update({
  id: '/claim-guest',
  path: '/claim-guest',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSplatRoute = ApiSplatRouteImport.update({
  id: '/api/$',
  path: '/api/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppActivityRoute = AppActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRouteRoute = AppSettingsRouteRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const HelpIndexRoute = HelpIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => HelpRoute,
} as any)
const HelpSlugRoute = HelpSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => HelpRoute,
} as any)
const InviteInvitationIdRoute = InviteInvitationIdRouteImport.update({
  id: '/invite/$invitationId',
  path: '/invite/$invitationId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSettingsIndexRoute = AppSettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppSettingsRouteRoute,
} as any)
const AppSettingsApiKeysRoute = AppSettingsApiKeysRouteImport.update({
  id: '/api-keys',
  path: '/api-keys',
  getParentRoute: () => AppSettingsRouteRoute,
} as any)
const AppSettingsProfileRoute = AppSettingsProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppSettingsRouteRoute,
} as any)
const AppGroupsGroupIdIndexRoute = AppGroupsGroupIdIndexRouteImport.update({
  id: '/groups/$groupId/',
  path: '/groups/$groupId/',
  getParentRoute: () => AppRoute,
} as any)
const AppGroupsGroupIdExpensesExpenseIdRoute =
  AppGroupsGroupIdExpensesExpenseIdRouteImport.update({
    id: '/groups/$groupId/expenses/$expenseId',
    path: '/groups/$groupId/expenses/$expenseId',
    getParentRoute: () => AppRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/claim-guest': typeof ClaimGuestRoute
  '/docs': typeof DocsRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/help': typeof HelpRouteWithChildren
  '/login': typeof LoginRoute
  '/mcp': typeof McpRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/verify-email': typeof VerifyEmailRoute
  '/app/settings': typeof AppSettingsRouteRouteWithChildren
  '/api/$': typeof ApiSplatRoute
  '/app/activity': typeof AppActivityRoute
  '/help/$slug': typeof HelpSlugRoute
  '/invite/$invitationId': typeof InviteInvitationIdRoute
  '/app/': typeof AppIndexRoute
  '/help/': typeof HelpIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/app/settings/api-keys': typeof AppSettingsApiKeysRoute
  '/app/settings/profile': typeof AppSettingsProfileRoute
  '/app/settings/': typeof AppSettingsIndexRoute
  '/app/groups/$groupId/': typeof AppGroupsGroupIdIndexRoute
  '/app/groups/$groupId/expenses/$expenseId': typeof AppGroupsGroupIdExpensesExpenseIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/claim-guest': typeof ClaimGuestRoute
  '/docs': typeof DocsRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/mcp': typeof McpRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/verify-email': typeof VerifyEmailRoute
  '/api/$': typeof ApiSplatRoute
  '/app/activity': typeof AppActivityRoute
  '/help/$slug': typeof HelpSlugRoute
  '/invite/$invitationId': typeof InviteInvitationIdRoute
  '/app': typeof AppIndexRoute
  '/help': typeof HelpIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/app/settings/api-keys': typeof AppSettingsApiKeysRoute
  '/app/settings/profile': typeof AppSettingsProfileRoute
  '/app/settings': typeof AppSettingsIndexRoute
  '/app/groups/$groupId': typeof AppGroupsGroupIdIndexRoute
  '/app/groups/$groupId/expenses/$expenseId': typeof AppGroupsGroupIdExpensesExpenseIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/claim-guest': typeof ClaimGuestRoute
  '/docs': typeof DocsRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/help': typeof HelpRouteWithChildren
  '/login': typeof LoginRoute
  '/mcp': typeof McpRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/verify-email': typeof VerifyEmailRoute
  '/app/settings': typeof AppSettingsRouteRouteWithChildren
  '/api/$': typeof ApiSplatRoute
  '/app/activity': typeof AppActivityRoute
  '/help/$slug': typeof HelpSlugRoute
  '/invite/$invitationId': typeof InviteInvitationIdRoute
  '/app/': typeof AppIndexRoute
  '/help/': typeof HelpIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/app/settings/api-keys': typeof AppSettingsApiKeysRoute
  '/app/settings/profile': typeof AppSettingsProfileRoute
  '/app/settings/': typeof AppSettingsIndexRoute
  '/app/groups/$groupId/': typeof AppGroupsGroupIdIndexRoute
  '/app/groups/$groupId/expenses/$expenseId': typeof AppGroupsGroupIdExpensesExpenseIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/claim-guest'
    | '/docs'
    | '/forgot-password'
    | '/help'
    | '/login'
    | '/mcp'
    | '/reset-password'
    | '/signup'
    | '/verify-email'
    | '/app/settings'
    | '/api/$'
    | '/app/activity'
    | '/help/$slug'
    | '/invite/$invitationId'
    | '/app/'
    | '/help/'
    | '/api/auth/$'
    | '/app/settings/api-keys'
    | '/app/settings/profile'
    | '/app/settings/'
    | '/app/groups/$groupId/'
    | '/app/groups/$groupId/expenses/$expenseId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/claim-guest'
    | '/docs'
    | '/forgot-password'
    | '/login'
    | '/mcp'
    | '/reset-password'
    | '/signup'
    | '/verify-email'
    | '/api/$'
    | '/app/activity'
    | '/help/$slug'
    | '/invite/$invitationId'
    | '/app'
    | '/help'
    | '/api/auth/$'
    | '/app/settings/api-keys'
    | '/app/settings/profile'
    | '/app/settings'
    | '/app/groups/$groupId'
    | '/app/groups/$groupId/expenses/$expenseId'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/claim-guest'
    | '/docs'
    | '/forgot-password'
    | '/help'
    | '/login'
    | '/mcp'
    | '/reset-password'
    | '/signup'
    | '/verify-email'
    | '/app/settings'
    | '/api/$'
    | '/app/activity'
    | '/help/$slug'
    | '/invite/$invitationId'
    | '/app/'
    | '/help/'
    | '/api/auth/$'
    | '/app/settings/api-keys'
    | '/app/settings/profile'
    | '/app/settings/'
    | '/app/groups/$groupId/'
    | '/app/groups/$groupId/expenses/$expenseId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  ClaimGuestRoute: typeof ClaimGuestRoute
  DocsRoute: typeof DocsRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  HelpRoute: typeof HelpRouteWithChildren
  LoginRoute: typeof LoginRoute
  McpRoute: typeof McpRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
  VerifyEmailRoute: typeof VerifyEmailRoute
  ApiSplatRoute: typeof ApiSplatRoute
  InviteInvitationIdRoute: typeof InviteInvitationIdRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/claim-guest': {
      id: '/claim-guest'
      path: '/claim-guest'
      fullPath: '/claim-guest'
      preLoaderRoute: typeof ClaimGuestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/$': {
      id: '/api/$'
      path: '/api/$'
      fullPath: '/api/$'
      preLoaderRoute: typeof ApiSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/activity': {
      id: '/app/activity'
      path: '/activity'
      fullPath: '/app/activity'
      preLoaderRoute: typeof AppActivityRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteRouteImport
      parentRoute: typeof AppRoute
    }
    '/help/': {
      id: '/help/'
      path: '/'
      fullPath: '/help/'
      preLoaderRoute: typeof HelpIndexRouteImport
      parentRoute: typeof HelpRoute
    }
    '/help/$slug': {
      id: '/help/$slug'
      path: '/$slug'
      fullPath: '/help/$slug'
      preLoaderRoute: typeof HelpSlugRouteImport
      parentRoute: typeof HelpRoute
    }
    '/invite/$invitationId': {
      id: '/invite/$invitationId'
      path: '/invite/$invitationId'
      fullPath: '/invite/$invitationId'
      preLoaderRoute: typeof InviteInvitationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/settings/': {
      id: '/app/settings/'
      path: '/'
      fullPath: '/app/settings/'
      preLoaderRoute: typeof AppSettingsIndexRouteImport
      parentRoute: typeof AppSettingsRouteRoute
    }
    '/app/settings/api-keys': {
      id: '/app/settings/api-keys'
      path: '/api-keys'
      fullPath: '/app/settings/api-keys'
      preLoaderRoute: typeof AppSettingsApiKeysRouteImport
      parentRoute: typeof AppSettingsRouteRoute
    }
    '/app/settings/profile': {
      id: '/app/settings/profile'
      path: '/profile'
      fullPath: '/app/settings/profile'
      preLoaderRoute: typeof AppSettingsProfileRouteImport
      parentRoute: typeof AppSettingsRouteRoute
    }
    '/app/groups/$groupId/': {
      id: '/app/groups/$groupId/'
      path: '/groups/$groupId'
      fullPath: '/app/groups/$groupId/'
      preLoaderRoute: typeof AppGroupsGroupIdIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/groups/$groupId/expenses/$expenseId': {
      id: '/app/groups/$groupId/expenses/$expenseId'
      path: '/groups/$groupId/expenses/$expenseId'
      fullPath: '/app/groups/$groupId/expenses/$expenseId'
      preLoaderRoute: typeof AppGroupsGroupIdExpensesExpenseIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppSettingsRouteRouteChildren {
  AppSettingsApiKeysRoute: typeof AppSettingsApiKeysRoute
  AppSettingsProfileRoute: typeof AppSettingsProfileRoute
  AppSettingsIndexRoute: typeof AppSettingsIndexRoute
}

const AppSettingsRouteRouteChildren: AppSettingsRouteRouteChildren = {
  AppSettingsApiKeysRoute: AppSettingsApiKeysRoute,
  AppSettingsProfileRoute: AppSettingsProfileRoute,
  AppSettingsIndexRoute: AppSettingsIndexRoute,
}

const AppSettingsRouteRouteWithChildren =
  AppSettingsRouteRoute._addFileChildren(AppSettingsRouteRouteChildren)

interface AppRouteChildren {
  AppSettingsRouteRoute: typeof AppSettingsRouteRouteWithChildren
  AppActivityRoute: typeof AppActivityRoute
  AppIndexRoute: typeof AppIndexRoute
  AppGroupsGroupIdIndexRoute: typeof AppGroupsGroupIdIndexRoute
  AppGroupsGroupIdExpensesExpenseIdRoute: typeof AppGroupsGroupIdExpensesExpenseIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppSettingsRouteRoute: AppSettingsRouteRouteWithChildren,
  AppActivityRoute: AppActivityRoute,
  AppIndexRoute: AppIndexRoute,
  AppGroupsGroupIdIndexRoute: AppGroupsGroupIdIndexRoute,
  AppGroupsGroupIdExpensesExpenseIdRoute:
    AppGroupsGroupIdExpensesExpenseIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface HelpRouteChildren {
  HelpSlugRoute: typeof HelpSlugRoute
  HelpIndexRoute: typeof HelpIndexRoute
}

const HelpRouteChildren: HelpRouteChildren = {
  HelpSlugRoute: HelpSlugRoute,
  HelpIndexRoute: HelpIndexRoute,
}

const HelpRouteWithChildren = HelpRoute._addFileChildren(HelpRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  ClaimGuestRoute: ClaimGuestRoute,
  DocsRoute: DocsRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  HelpRoute: HelpRouteWithChildren,
  LoginRoute: LoginRoute,
  McpRoute: McpRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
  VerifyEmailRoute: VerifyEmailRoute,
  ApiSplatRoute: ApiSplatRoute,
  InviteInvitationIdRoute: InviteInvitationIdRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
