/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/app'
import { Route as LoginRouteImport } from './routes/login'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ApiSplatRouteImport } from './routes/api/$'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as AppSettingsRouteImport } from './routes/app/settings'
import { Route as InviteInvitationIdRouteImport } from './routes/invite/$invitationId'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AppGroupsNewRouteImport } from './routes/app/groups/new'
import { Route as AppGroupsGroupIdIndexRouteImport } from './routes/app/groups/$groupId/index'
import { Route as AppGroupsGroupIdExpensesExpenseIdRouteImport } from './routes/app/groups/$groupId/expenses/$expenseId'
import { Route as AppGroupsGroupIdExpensesNewRouteImport } from './routes/app/groups/$groupId/expenses/new'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSplatRoute = ApiSplatRouteImport.update({
  id: '/api/$',
  path: '/api/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const InviteInvitationIdRoute = InviteInvitationIdRouteImport.update({
  id: '/invite/$invitationId',
  path: '/invite/$invitationId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AppGroupsNewRoute = AppGroupsNewRouteImport.update({
  id: '/groups/new',
  path: '/groups/new',
  getParentRoute: () => AppRoute,
} as any)
const AppGroupsGroupIdIndexRoute = AppGroupsGroupIdIndexRouteImport.update({
  id: '/groups/$groupId/',
  path: '/groups/$groupId/',
  getParentRoute: () => AppRoute,
} as any)
const AppGroupsGroupIdExpensesExpenseIdRoute =
  AppGroupsGroupIdExpensesExpenseIdRouteImport.update({
    id: '/groups/$groupId/expenses/$expenseId',
    path: '/groups/$groupId/expenses/$expenseId',
    getParentRoute: () => AppRoute,
  } as any)
const AppGroupsGroupIdExpensesNewRoute =
  AppGroupsGroupIdExpensesNewRouteImport.update({
    id: '/groups/$groupId/expenses/new',
    path: '/groups/$groupId/expenses/new',
    getParentRoute: () => AppRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/mcp': typeof McpRoute
  '/signup': typeof SignupRoute
  '/api/$': typeof ApiSplatRoute
  '/app/settings': typeof AppSettingsRoute
  '/invite/$invitationId': typeof InviteInvitationIdRoute
  '/app/': typeof AppIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/app/groups/new': typeof AppGroupsNewRoute
  '/app/groups/$groupId/': typeof AppGroupsGroupIdIndexRoute
  '/app/groups/$groupId/expenses/$expenseId': typeof AppGroupsGroupIdExpensesExpenseIdRoute
  '/app/groups/$groupId/expenses/new': typeof AppGroupsGroupIdExpensesNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/mcp': typeof McpRoute
  '/signup': typeof SignupRoute
  '/api/$': typeof ApiSplatRoute
  '/app/settings': typeof AppSettingsRoute
  '/invite/$invitationId': typeof InviteInvitationIdRoute
  '/app': typeof AppIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/app/groups/new': typeof AppGroupsNewRoute
  '/app/groups/$groupId': typeof AppGroupsGroupIdIndexRoute
  '/app/groups/$groupId/expenses/$expenseId': typeof AppGroupsGroupIdExpensesExpenseIdRoute
  '/app/groups/$groupId/expenses/new': typeof AppGroupsGroupIdExpensesNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/mcp': typeof McpRoute
  '/signup': typeof SignupRoute
  '/api/$': typeof ApiSplatRoute
  '/app/settings': typeof AppSettingsRoute
  '/invite/$invitationId': typeof InviteInvitationIdRoute
  '/app/': typeof AppIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/app/groups/new': typeof AppGroupsNewRoute
  '/app/groups/$groupId/': typeof AppGroupsGroupIdIndexRoute
  '/app/groups/$groupId/expenses/$expenseId': typeof AppGroupsGroupIdExpensesExpenseIdRoute
  '/app/groups/$groupId/expenses/new': typeof AppGroupsGroupIdExpensesNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/login'
    | '/mcp'
    | '/signup'
    | '/api/$'
    | '/app/settings'
    | '/invite/$invitationId'
    | '/app/'
    | '/api/auth/$'
    | '/app/groups/new'
    | '/app/groups/$groupId/'
    | '/app/groups/$groupId/expenses/$expenseId'
    | '/app/groups/$groupId/expenses/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/mcp'
    | '/signup'
    | '/api/$'
    | '/app/settings'
    | '/invite/$invitationId'
    | '/app'
    | '/api/auth/$'
    | '/app/groups/new'
    | '/app/groups/$groupId'
    | '/app/groups/$groupId/expenses/$expenseId'
    | '/app/groups/$groupId/expenses/new'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/login'
    | '/mcp'
    | '/signup'
    | '/api/$'
    | '/app/settings'
    | '/invite/$invitationId'
    | '/app/'
    | '/api/auth/$'
    | '/app/groups/new'
    | '/app/groups/$groupId/'
    | '/app/groups/$groupId/expenses/$expenseId'
    | '/app/groups/$groupId/expenses/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  McpRoute: typeof McpRoute
  SignupRoute: typeof SignupRoute
  ApiSplatRoute: typeof ApiSplatRoute
  InviteInvitationIdRoute: typeof InviteInvitationIdRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/$': {
      id: '/api/$'
      path: '/api/$'
      fullPath: '/api/$'
      preLoaderRoute: typeof ApiSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/invite/$invitationId': {
      id: '/invite/$invitationId'
      path: '/invite/$invitationId'
      fullPath: '/invite/$invitationId'
      preLoaderRoute: typeof InviteInvitationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/groups/new': {
      id: '/app/groups/new'
      path: '/groups/new'
      fullPath: '/app/groups/new'
      preLoaderRoute: typeof AppGroupsNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/groups/$groupId/': {
      id: '/app/groups/$groupId/'
      path: '/groups/$groupId'
      fullPath: '/app/groups/$groupId/'
      preLoaderRoute: typeof AppGroupsGroupIdIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/groups/$groupId/expenses/$expenseId': {
      id: '/app/groups/$groupId/expenses/$expenseId'
      path: '/groups/$groupId/expenses/$expenseId'
      fullPath: '/app/groups/$groupId/expenses/$expenseId'
      preLoaderRoute: typeof AppGroupsGroupIdExpensesExpenseIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/groups/$groupId/expenses/new': {
      id: '/app/groups/$groupId/expenses/new'
      path: '/groups/$groupId/expenses/new'
      fullPath: '/app/groups/$groupId/expenses/new'
      preLoaderRoute: typeof AppGroupsGroupIdExpensesNewRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppSettingsRoute: typeof AppSettingsRoute
  AppIndexRoute: typeof AppIndexRoute
  AppGroupsNewRoute: typeof AppGroupsNewRoute
  AppGroupsGroupIdIndexRoute: typeof AppGroupsGroupIdIndexRoute
  AppGroupsGroupIdExpensesExpenseIdRoute: typeof AppGroupsGroupIdExpensesExpenseIdRoute
  AppGroupsGroupIdExpensesNewRoute: typeof AppGroupsGroupIdExpensesNewRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppSettingsRoute: AppSettingsRoute,
  AppIndexRoute: AppIndexRoute,
  AppGroupsNewRoute: AppGroupsNewRoute,
  AppGroupsGroupIdIndexRoute: AppGroupsGroupIdIndexRoute,
  AppGroupsGroupIdExpensesExpenseIdRoute:
    AppGroupsGroupIdExpensesExpenseIdRoute,
  AppGroupsGroupIdExpensesNewRoute: AppGroupsGroupIdExpensesNewRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  McpRoute: McpRoute,
  SignupRoute: SignupRoute,
  ApiSplatRoute: ApiSplatRoute,
  InviteInvitationIdRoute: InviteInvitationIdRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
